name: timeseries
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - conda-forge::geopandas
  - contextily
  - jupyter
  - conda-forge::rioxarray
  - conda-forge::xgboost
  - seaborn
  - anaconda::statsmodels
  - pip:
    - flaml[automl]